### ISSUE TITLE
Event data structure

### ISSUE THREAD

**Issue by paulmthompson** [paulmthompson/Spikes.jl#3]
Right now the event data structure specifies: 1) The index of time stamps it is associated with; and 2) the experiment time when it occurs (relative to start of experiment). I envisioned this to be used as a way for the user to specify a time and have methods to collect stamps in some window around this time (for instance, mark all spikes 1 second before to 1 second after the event).Since the spikes are sorted in time, a unitrange, is a nice compact way to store the location of perhaps many spikes in a compact way.

There should probably be more to this data structure though. I was collecting events in an array with rows indicating trials and columns indicating an event type. This is kind of limiting, because in some experiments, trials don't necessarily always have the same number of events, and they don't always occur in the same order.

It might be better for the event type to also contain some kind of ID field to specify the event type, and maybe another field to indicate the trial number, if applicable. Then methods to make something like a PSTH would collect all spikes around the event with a specified ID.

**Comment by alexmorley** [comment]
So we add two fields. ID (a string?) and trial number (Int) to the event type and then we have no need for the centre field for SpikeTimes...?

**Comment by paulmthompson** [comment]
Yeah I think having the ID and trial fields will completely remove any need for the center field (and be much less confusing than what I currently have :) ).

I think we might get better performance with both fields being integers, so that the compiler knows exactly how many bytes each event is, and they can pack together in arrays with no pointers.

We could probably use an optional dictionary interface that will relate event IDs as strings with the Int value stored in the events datatype. So for example you could make a psth with calls like

plot_psth(myspiketrain, event="target_onset")

 or equivalently

plot_psth(myspiketrain, event=3)

Maybe this could be stored in the spike train type?

**Comment by alexmorley** [comment]
Yep I'm sure your right. Dictionary in SpikeTrain sounds like a good solution. I'll try and get something along those lines working this evening.
